// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJLOaSAuQpeVl_lA44_7RUQNxxPrTL1jY',
    appId: '1:634781427189:web:189b8bf25267bff6136cbc',
    messagingSenderId: '634781427189',
    projectId: 'quiz-app-firebase-caddf',
    authDomain: 'quiz-app-firebase-caddf.firebaseapp.com',
    storageBucket: 'quiz-app-firebase-caddf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Z8_MpxoxVGjoBz-XNFXDtbYgJ8wSrSo',
    appId: '1:634781427189:android:49c70efc2f15a4ed136cbc',
    messagingSenderId: '634781427189',
    projectId: 'quiz-app-firebase-caddf',
    storageBucket: 'quiz-app-firebase-caddf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQjPVDmtf5nbXIUmJ1m15Av8DDUIJotDc',
    appId: '1:634781427189:ios:8c8e4115aef808a9136cbc',
    messagingSenderId: '634781427189',
    projectId: 'quiz-app-firebase-caddf',
    storageBucket: 'quiz-app-firebase-caddf.appspot.com',
    iosClientId: '634781427189-6p11e1snledpm5el7smlpi2uuhnahjcv.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQjPVDmtf5nbXIUmJ1m15Av8DDUIJotDc',
    appId: '1:634781427189:ios:745f1c2f089b3e35136cbc',
    messagingSenderId: '634781427189',
    projectId: 'quiz-app-firebase-caddf',
    storageBucket: 'quiz-app-firebase-caddf.appspot.com',
    iosClientId: '634781427189-57hoagpnmubm6g2bq7p876mfnr8k81st.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizAppFirebase.RunnerTests',
  );
}
